<div id="work">
  <div class="my-5 px-md-3 max-w">
    <div class="font-m">
      <h2 class="font-shiny text-center font-m mb-5 pb-3">
        Global Weirding
      </h2>
      <p class="font-shiny">
        Obviously there is more going on in the extraordinary experiences of our psychonauts than the intimations of an emerging network society. But from the claustrophobic perspective of our current moment, this is the contextual framework that has seemed most pressing to me—the most resonant. Today we must penetrate, navigate, and play the game of reality as never before, even as it plays us to the hilt. These are archon times, my friends, and grappling with high weirdness may paradoxically be a kind of mental health regimen. The network visions served up by our psychonauts are not melty New Age custards of harmonic global fusion, but daemonic encounters in a postwar labyrinth that the CIA spook James Jesus Angleton called a “wilderness of mirrors.” At the same time, the Outside we occasionally glimpse through cracks in the glass––cosmic and extraterrestrial or animist and planetary—remains stubbornly irreducible to the mere technical circulation of signs and affects. These guys wrestled with angels in the gutters of Moloch. Their systems mysticism is, in this sense, less important than their prophecies of weirdness on a planetary scale.
      </p>
      <p class="font-shiny">
        The turn towards the weird in contemporary theory, briefly discussed in the introduction, is itself a symptom of a broader shift in consciousness, culture, and material conditions that amplifies this once marginalized word, into something that is at once a concept, a cultural space, and a mode of being. The weirding of our contemporary world no longer exactly means the “classic” weird—the weirdness that coursed through and congealed in pulp fictions, druggy subcultures, “counterhegemonic narratives,” and all manner of profane and heretical scenes and practices. Like so many undergrounds, that weird has become a cultural standing reserve, a raw material to fuel media's need for the simultaneously new and familiar. The weird that saturates culture today is present often through its memetic banalization, like magical sigils serving as corporate logos. After all, much of the material in this book—garish genre fictions, strange psychedelic drugs, occult arcana, esoteric rituals, conspiracy theories—is now thoroughly mainstream.
      </p>
      <p class="font-shiny">
        I have been writing about and wrestling with this marginal stuff for over thirty years. This means two things: that they weren't that marginal really, and that I directly contributed to making them even less so. Nonetheless, I am regularly shocked these days with the degree to which once outré signifiers of the fringe—like Burning Man, or the occult rocket scientist Jack Parsons, or the heavy-duty what-the-fuck of DMT—have become part of common conversation and common consumption. Even the academy, which long resisted this kind of greasy kid stuff, has turned on. Ayahuasca tourism, left-hand-path occultism, the history of Bigfoot—all are fair game for a tart little study.
      </p>
      <p class="font-shiny">
        This book, which began its life as a PhD dissertation at a reasonably prestigious university, is further evidence of that shift. Again, mea culpa. But while I'll take some of the responsibility for helping to drain the taboo charge from the weird, I prefer to think that I am part of a mass transmission of arcane encounter—a psychedelic contagion—that is best likened to having bubble-gum stuck on your shoe, some oddly scented but vaguely repellent mass that you can't pick off the sole, which means that it gets all over your hands, and in the end you can do nothing else but pass it on to whomever you meet. Here you go. Good luck with it.
      </p>
      <p class="font-shiny">
        But I am also convinced that there are pressing reasons to wrestle with the weird these days. The first is the extraordinary and unprecedented shift in the developed world's attitude towards psychedelic compounds. Between researchers and clinicians hyping the therapeutic powers of these drugs, and the explosion of mainstream interest in “shamanic” experiences, psychedelics have come fully into the contemporary light. But the psychedelic renaissance has, in part, required the active forgetting of the bohemian and countercultural legacy of psychedelic use within the West. Part of the impetus of this study has been to remember these stories, and to insist, on both a psychocultural and ontological level, that psychedelics are not just about healing traumas or experiencing unity consciousness or supercharging dance music. No, folks, psychedelics are about encountering zones and beings and modes of experience that are, whatever else might be said, deeply fucking weird. That weirdness is repressed as part of the current medicalization and pop-culture normalization of psychedelic drugs. And you don't need to be an acolyte of that old cigar-puffing Viennese psychonaut to know what happens when you repress such daemonic forces.
      </p>
      <p class="font-shiny">
        The psychedelic renaissance exists partly because of the obvious therapeutic, spiritual, and even ecological value of these allies. But there is another, less visible reason for their popularity now. Simply put, psychedelic experience resonates with today's vertiginous networking of consciousness and culture. Many of the themes explored in this study—the charisma of conspiracy theories, the possibility of nonhuman intelligence, the confusion of fact and fiction, the scripting of the self—are now part of our common hypermediated condition. The countercultural influence on cyberculture was not just about hippie hackers or the social freedoms that fuel an entrepreneurial economy of innovation. This underground influence also speaks to the fact that contemporary technologies are, literally, mind-manifesting. Consciousness, consensus reality, and even matter itself are increasingly shaped—warped, shattered, expanded—by their use. A deep familiarity with psychedelic phenomenology is simply a good skill to possess in an era of memetic struggle, of virtual realities, of archon stratagems.
      </p>
      <p class="font-shiny">
        But it's not just information technology that is making our world weirder. The world itself, or rather the planet that substantiates the world, is not only suffering through the holocaust of a myriad of beings and species, but is losing the relatively stable climate that has sheltered the last ten thousand years of human history. It is not for nothing that global warming is often referred to as global weirding. The planet is not just getting hotter; it is growing more turbulent and unpredictable, more tricksy, and more defiantly wayward. Humans helped make this mess, and humans (or some of them) understand that fact, but tragically—ironically—we seemingly can do little about it. This creates a deeply uncanny condition of tortured knowledge and zombie-like inertia, as we collectively run the mad genius of petrochemical modernity into the dead and dusty ground. It is as if civilization made a sorcerous pact with petroleum genies, and the debt is now coming due.
      </p>
      <p class="font-shiny">
        If we are to embrace the reality of climate change, and if we are to reckon with all the nonhumans—biological or otherwise—whose destinies our now tied to ours, then we have to seek and demand an encounter with a Real beyond the symbolic frameworks of consciousness and culture, beyond the tidal surge of electronic reports, narcissistic loops, and memetic brainwash. Creatively worked, and suitably expanded, the human imagination can serve as an interface to entities and realities that elude the normal nets of rationality, language, and cultural symbols. We might never overcome the distortions of this interface, which means that we are condemned to shadow-box with our own scripts and specters even as we struggle to see. And yet, the Beyond beckons us, the Outside pulls us within, and the Other stages encounters that will change us in ways we cannot control or predict or even desire. But such is our wyrd.
      </p>
      <div class="text-center my-5">
        <img src="works/erikdavis/global-weirding.png" />
      </div>
    </div>
  </div>
</div>